# Generated by Django 5.0.8 on 2024-08-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80, verbose_name='full name')),
                ('phone', models.CharField(max_length=11, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='phone number')),
                ('token', models.CharField(max_length=11, verbose_name='token')),
                ('code', models.CharField(max_length=11, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
